version: '3.1'

services:

  mongo:
    image: mongo:latest
    container_name: mongodb-log
    environment:
      MONGO_INITDB_ROOT_USERNAME: gerente
      MONGO_INITDB_ROOT_PASSWORD: log_user2023_gerente

  websvr:
    build: ./work
    container_name: web4mongo-log
    volumes:  
      - ./work/app:/var/www/html
    ports:
      - 8082:80
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      MONGODB_USERNAME: gerente
      MONGODB_PASSWORD: log_user2023_gerente
      MONGODB_DB: Registro

  mongo-express:
    image: mongo-express:latest
    container_name: mongoex-log
    ports:
      - 8081:8081     
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: gerente
      ME_CONFIG_MONGODB_ADMINPASSWORD: log_user2023_gerente
      ME_CONFIG_MONGODB_URL: mongodb://gerente:log_user2023_gerente@mongo:27017/
    links:
      - mongo
    depends_on:
      - mongo